/*
 * RemoveDialog.java
 *
 * Created on 12 de Janeiro de 2009, 11:25
 */

package br.ufpb.di.mic2;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  Duilio
 */
public class RemoveDialog extends javax.swing.JDialog {

     static final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private static final Dimension appSize = new Dimension(320, 145);
    private static final int appPosX = (screenSize.width / 2) - (appSize.width / 2);
    private static final int appPosY = (int)(screenSize.height / 1.95) - (appSize.height / 2);
    private static Rectangle appBounds = new Rectangle(appPosX, appPosY, appSize.width, appSize.height);
    
     javax.swing.JPanel contentpanel = null;
    private String codHexa;
    private int codDec;
    private int numMicroInstrucoes;
    
    public EscreveMicroProg emp = new EscreveMicroProg();
    
    /** Creates new form RemoveDialog */
    public RemoveDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        initComponents();
        setBounds(appBounds);
        initContentPane();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover Instrução");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número de MicroInstruções:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setText("Código Hexadecimal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 90, -1));

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 48, 120, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 18, 120, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    codHexa = jTextField2.getText();
    Boolean continua = true;
    
    if(codHexa.contains("0x")== true){
        char array[] = codHexa.toCharArray();
    char arrayAux[] = new char[array.length  - 2];
    if(arrayAux.length == 0){
        continua = false;
        javax.swing.JOptionPane.showMessageDialog(null, "Código hexadecimal inválido!","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        
    }
        int k =0;
        for(int i = 0; i<array.length; i++){
            if(i>1){
                arrayAux[k] = array[i];
                k++;
             }
        
        }
    
        codHexa = String.valueOf(arrayAux);
        
    
    }
    
    else{
        javax.swing.JOptionPane.showMessageDialog(null, "Código hexadecimal inválido! Insira o código começando por 0x e tente novamente.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        continua = false;
    }
    
    if(continua == true) {
        
        String aux = jTextField1.getText();
        Boolean b = validaCodHexa(codHexa);
        if(b == false){
            javax.swing.JOptionPane.showMessageDialog(null, "Código hexadecimal inválido! Tente novamente.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            continua = false;
        }
         else if(aux.equals("") == true ){
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor insira o número de microinstruções e tente novamente.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            continua = false;
         }
         else if (aux.equals("") == false){
            try{
                numMicroInstrucoes = Integer.parseInt(aux); 
            }
            catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, "Número de Microinstruções inválido! Tente novamente.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
                continua = false;
            }
        
         }
        
        if(continua == true){
            
            codDec = Main.mf.conv.HexatoDec(codHexa);
            setVisible(false);
            if(codDec<511){
                emp.Remove(codDec,numMicroInstrucoes);
            }
            else
                javax.swing.JOptionPane.showMessageDialog(null, "Código hexadecimal além do limite! ( 0-512 )");
            
            
             //faz o resto aki
        }
    
    }
}//GEN-LAST:event_jButton2ActionPerformed

    public Boolean validaCodHexa(String a){
        
        char array[] = a.toCharArray();
        
        Boolean b = true;
        for(int i = 0; i<array.length; i++){
            
            if(array[i]!= '0'&& array[i]!= '1'&& array[i]!= '2'&& array[i]!= '3'&& array[i]!= '4'&& array[i]!= '5'
                    && array[i]!= '6'&& array[i]!= '7'&& array[i]!= '8'&& array[i]!= '9'&& array[i]!= 'A'&& array[i]!= 'B'
                    && array[i]!= 'C'&& array[i]!= 'D'&& array[i]!= 'E'&& array[i]!= 'F'){
                b =false;
                break;
            }
            else
                b = true;
        }
        return b;
        
    }
    public void initContentPane(){
        contentpanel = new javax.swing.JPanel(new BorderLayout());
        contentpanel.add(jPanel1,BorderLayout.CENTER);
        this.setContentPane(contentpanel);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RemoveDialog dialog = new RemoveDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
